"""empty message

Revision ID: 46fb47f64f88
Revises: dc9ee00c3657
Create Date: 2024-06-12 10:35:43.252883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46fb47f64f88'
down_revision = 'dc9ee00c3657'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('child_id', sa.Integer(), nullable=False),
    sa.Column('goal_id', sa.Integer(), nullable=True),
    sa.Column('child_username', sa.String(), nullable=False),
    sa.Column('chores_id', sa.Integer(), nullable=True),
    sa.Column('goal_name', sa.String(), nullable=True),
    sa.Column('chores_name', sa.String(), nullable=True),
    sa.Column('chores_status', sa.String(), nullable=True),
    sa.Column('goal_complete', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['child_id'], ['child.id'], ),
    sa.ForeignKeyConstraint(['child_username'], ['child.username'], ),
    sa.ForeignKeyConstraint(['chores_id'], ['chores.id'], ),
    sa.ForeignKeyConstraint(['goal_id'], ['goal.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chores', schema=None) as batch_op:
        batch_op.drop_column('status')

    with op.batch_alter_table('goal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_complete', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goal', schema=None) as batch_op:
        batch_op.drop_column('_complete')

    with op.batch_alter_table('chores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True))

    op.drop_table('notifications')
    # ### end Alembic commands ###
