"""empty message

Revision ID: f5fd21d6e5a9
Revises: 6ecda0990bd5
Create Date: 2024-06-02 15:06:43.199561

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5fd21d6e5a9'
down_revision = '6ecda0990bd5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('img', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('link', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goal', schema=None) as batch_op:
        batch_op.drop_column('description')
        batch_op.drop_column('link')
        batch_op.drop_column('img')

    # ### end Alembic commands ###
