"""empty message

Revision ID: f85e1aa4123c
Revises: fc3b4ffa9d09
Create Date: 2024-06-05 11:55:36.513427

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f85e1aa4123c'
down_revision = 'fc3b4ffa9d09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('child', schema=None) as batch_op:
        batch_op.add_column(sa.Column('img', sa.String(), nullable=False))
        batch_op.drop_column('profile_img')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('child', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_img', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.drop_column('img')

    # ### end Alembic commands ###
